// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNoVtcn5gv1jeyWi_qcY06lvVXuWyFEXA',
    appId: '1:1068782096092:web:02d66b67c8ae9d4813ee19',
    messagingSenderId: '1068782096092',
    projectId: 'libreria-6a1ed',
    authDomain: 'libreria-6a1ed.firebaseapp.com',
    storageBucket: 'libreria-6a1ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvzmdwIxsNB6w6b8Wlu4FBGIWmXiDhPKM',
    appId: '1:1068782096092:android:61c2b37f9dbf616c13ee19',
    messagingSenderId: '1068782096092',
    projectId: 'libreria-6a1ed',
    storageBucket: 'libreria-6a1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Y9W23QCFrzk0WY7z_0coVGTAm4XByRY',
    appId: '1:1068782096092:ios:a2345cff1b3fc39b13ee19',
    messagingSenderId: '1068782096092',
    projectId: 'libreria-6a1ed',
    storageBucket: 'libreria-6a1ed.firebasestorage.app',
    androidClientId: '1068782096092-vgur49g2gcsgik16e87726aprlb7v90h.apps.googleusercontent.com',
    iosClientId: '1068782096092-n299p0f2mechfmhcqf60i2km635rhcpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.libreriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Y9W23QCFrzk0WY7z_0coVGTAm4XByRY',
    appId: '1:1068782096092:ios:a2345cff1b3fc39b13ee19',
    messagingSenderId: '1068782096092',
    projectId: 'libreria-6a1ed',
    storageBucket: 'libreria-6a1ed.firebasestorage.app',
    androidClientId: '1068782096092-vgur49g2gcsgik16e87726aprlb7v90h.apps.googleusercontent.com',
    iosClientId: '1068782096092-n299p0f2mechfmhcqf60i2km635rhcpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.libreriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNoVtcn5gv1jeyWi_qcY06lvVXuWyFEXA',
    appId: '1:1068782096092:web:7a3c8810a16df41813ee19',
    messagingSenderId: '1068782096092',
    projectId: 'libreria-6a1ed',
    authDomain: 'libreria-6a1ed.firebaseapp.com',
    storageBucket: 'libreria-6a1ed.firebasestorage.app',
  );
}
